tfe         :
  org_token :
    org     : jawn

github_actions           :
  env_secret             :
    automating_terraform :
      repository         : automating-terraform
      secret_name        : TF_API_TOKEN
      plaintext_value    : ""