provider:
  github:
    token: ""
    owner: javvn

local_file:
  tfe_token_payload:
    filename: ./scripts/payload.json
    content:
      data:
        type: authentication-tokens
        attributes:
          description: Automating-Terraform-GitHub-Actions

github_actions        :
  secret              :
    tfe_token         :
      repository      : automating-terraform
      secret_name     : TF_API_TOKEN
      plaintext_value : ""


data:
  local_file:
    tfe_token:
      filename: ./scripts/.tfe_token